services:
  - type: web
    name: college-football-voting-app
    env: python
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ..
      rm -rf backend/static && mkdir -p backend/static
      cp -r frontend/out/* backend/static/
      cd backend && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: college-football-voting-db
          property: connectionString
      - key: NEXT_PUBLIC_API_URL
        value: https://college-football-voting-app.onrender.com
    healthCheckPath: /health

databases:
  - name: college-football-voting-db
    databaseName: football_votes
    user: football_user
    plan: free 