services:
  - type: web
    name: college-football-voting-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: college-football-voting-db
          property: connectionString

databases:
  - name: college-football-voting-db
    databaseName: football_votes
    user: football_user
    plan: free 