services:
  - type: web
    name: college-football-backend
    env: python
    plan: free
    buildCommand: |
      cd backend && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: college-football-voting-db
          property: connectionString
    healthCheckPath: /health

  - type: web
    name: college-football-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
    startCommand: |
      cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: NEXT_PUBLIC_API_URL
        value: https://college-football-backend.onrender.com

databases:
  - name: college-football-voting-db
    databaseName: football_votes
    user: football_user
    plan: free 